// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DemoMVC.Data;
namespace DemoMVC.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210920005316_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("MvcMovie.Models.Student", b =>
                {
                    b.Property<int>("studentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Countryside")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("birthDay")
                        .HasColumnType("TEXT");

                    b.Property<string>("studentName")
                        .HasColumnType("TEXT");

                    b.HasKey("studentID");

                    b.ToTable("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
